In [4]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as mt
import math 

In [5]:
df=pd.read_excel("MultipleRegression.xlsx",sheet_name="Sheet1")#Get Data From Excel File
df

Area  Badroom  Age   Price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [6]:
Badroom_mediam=math.floor(df.Badroom.median())#Get Median
Badroom_mediam

3

In [7]:
df.Badroom=df.Badroom.fillna(Badroom_mediam)

In [8]:
df

Area  Badroom  Age   Price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      3.0   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [9]:
reg=linear_model.LinearRegression()
reg.fit(df[['Area','Badroom','Age']],df.Price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [10]:
reg.predict([[2600,3,1]])

array([655675.])

In [11]:
#By Pickle Method
import pickle#To Save

In [12]:
with open('model_pickle','wb') as f:
    pickle.dump(reg,f)

In [13]:
#To Read
import pickle

In [14]:
with open('model_pickle','rb') as f:
    res=pickle.load(f)

In [15]:
res.predict([[2600,3,1]])#NOTE you will get same output as above

array([655675.])

In [16]:
#By Joblib Method
from sklearn.externals import joblib


In [17]:
joblib.dump(reg,'Joblib_Model')#To Store

['Joblib_Model']

In [18]:
r=joblib.load('Joblib_Model')#To Read
r.predict([[2600,3,1]])

array([655675.])