In [14]:
import pandas as pd

In [15]:
df=pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [16]:
df.groupby("Category").describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [17]:
#To Change String to Numaric of Category Column
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Category']=le.fit_transform(df.Category)

In [18]:
df.head()

Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...

In [19]:
#Split Datasetinto Train Test DataSet
from sklearn.model_selection import train_test_split
X_Train,X_Test,Y_Train,Y_Test=train_test_split(df.Message,df.Category,test_size=0.2)


In [20]:
#To Convert Message into Digit We Used Vector in Which we create the unique word to the entire messages t
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
X_Train_Count=v.fit_transform(X_Train.values)
X_Train_Count.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [21]:
#Apply Multinomial Naive Bayes Method
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_Train_Count,Y_Train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [22]:
#Testing Phase
emails = [
    "Hay this is Discount Season Upto %50 Do CheckOut right now",
    "When You Comming Mall for Shopping"
    
]

emails_count=v.transform(emails)

model.predict(emails_count)

array([1, 0], dtype=int64)

In [23]:
#Get Accuracy
X_Test_Count=v.transform(X_Test.values)
model.score(X_Test_Count,Y_Test)

0.9865470852017937

In [24]:
#Now We Used Pipeline insted of Conversion of Emails into Digit and Further Steps Pipeline does all of these Steps by its Own
from sklearn.pipeline import Pipeline
clf=Pipeline([
    ("Vectorizer",CountVectorizer()),
    ("nb",MultinomialNB())
])

In [25]:
clf.fit(X_Train,Y_Train)

Pipeline(memory=None,
     steps=[('Vectorizer', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)), ('nb', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])

In [26]:
clf.predict(X_Test)

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)